### ISSUE TITLE
Activity Plots without Titles

### ISSUE THREAD

**Issue by benory** [benory/1520s-project-website#2]
On the work pages, it would be better for the two activity plots to not have titles to reduce redundancy with the metadata listed above. 

Can we render new versions of these images without titles?

**Comment by craigsapp** [comment]
Yes that should be possible.  I will make two versions: one with a title and one without depending on which is most useful in a given setting.

**Comment by craigsapp** [comment]
Implement with commit https://github.com/benory/1520s-project-website/commit/09120fbcae082c402ddebefc8664b14acbe6e06d

There are two styles for the plots now, one with title and one without:

https://data.1520s-project.org/Snf0105-activity-merged.png

https://data.1520s-project.org/Snf0105-activity-merged-notitle.png

Example of the update on a work page:

https://1520s-project.org/work/?id=Snf0105

<img width="1020" alt="Screenshot 2024-01-21 at 22 08 54" src="https://github.com/benory/1520s-project-website/assets/3487289/d95d23a0-1e6a-40bf-bd19-016eecc76d2e">

**Comment by craigsapp** [comment]
Commit https://github.com/benory/1520s-project-website/commit/4b60b50cf7d5b4d9c735f4766595a84720afa482 adds a new feature (which you can undo if you do not want it):  if you click on the activity plot(s) they will be downloaded (in full scale).  Also clicking on the voice range plot will open it at full size in another window.

This is useful if you want to see more detail in the plots.  The downloaded png images include the title (which can be cropped in cases where the title is not needed).   Ideally the png images would be displayed in another window as with the vocal range SVG images, but this is mostly dependent on settings in the users' browser.  I might be able to force it to open in a window rather than being downloaded immediately by setting the image to be inlined in the URL headers on the data server.

Here is the result of clicking on the SVG image of the vocal ranges, which displays in a separate window:

<img width="1117" alt="Screenshot 2024-01-21 at 22 24 14" src="https://github.com/benory/1520s-project-website/assets/3487289/9c147fd5-79cf-4ddb-88d4-c127d3ef92ec">
